### ISSUE TITLE
Frame per second

### ISSUE THREAD

**Issue by WilliamFreau** [sp-engineering/frigate-viewer#10]
Hello,

I think there is a bug with the refresh per seconds. If you configure 10 FPS in parameter, you will have 1 frame per 10 seconds.
If you put 2 FPS in parameter, you will have 1 frame each two seconds.

I think you save the FPS in parameter, but in the CameraList the `refreshFrequency` is multiply by `1000`.

https://github.com/sp-engineering/frigate-viewer/blob/master/views%2Fcameras-list%2FCameraTile.tsx#L105

Have a nice day & Best regards

**Comment by jagauthier** [comment]
I just started using this app.   There isn't a FPS setting.  It says "Image refresh frequency (seconds)".
So you get 1 frame per that many seconds.

**Comment by WilliamFreau** [comment]
Oh, I see the difference of interpretation

I've understand this as `How many images I want to see per seconds` and not `Number of seconds between images`.

Since this is 6 month old, I'll close the issue.
Thanks :smile:

**Comment by jagauthier** [comment]
2 months, but okay.
