### ISSUE TITLE
Auth? 

### ISSUE THREAD

**Issue by har-lock** [sp-engineering/frigate-viewer#11]
When opening the app, i see fields for username and password 

What do you use for that auth on the server side ?

Because frigate doesn't have a login interface

**Comment by potchin** [comment]
Its only possible when frigate is behind a reverse proxy (eg https://docs.frigate.video/guides/reverse_proxy/#step-3-authenticate-users-at-the-proxy).

Note that it isnt fully supported yet - see #5

**Comment by piwko28** [comment]
Not related to the mobile app; above is explanation. I'm closing the issue.
