### ISSUE TITLE
Video clips are moving up and down on every refresh

### ISSUE THREAD

**Issue by SlavikCA** [sp-engineering/frigate-viewer#12]
I see the refresh to every 2 seconds.

And on every refresh, that images of every camera moves up and down

**Comment by SlavikCA** [comment]
https://github.com/sp-engineering/frigate-viewer/assets/6293679/6f2d0298-471b-4a15-926b-b4ea8da85f99

**Comment by piwko28** [comment]
Thanks for reporting it and attaching the video.

**Comment by piwko28** [comment]
I made some changes, but cannot test it. I'll mark it as closed, please reopen it if you will stll occur these issues after update the app to 14.0.0.
