### ISSUE TITLE
Network request failed

### ISSUE THREAD

**Issue by batman99000** [sp-engineering/frigate-viewer#3]
Just started using frigate myself not too long ago. However, when I try to use your app to view my cameras, it always brings up a toast Message saying network request failed. 

If it helps, I am using traefik on my local network for a reverse proxy, and that configuration is working as expected. I can access and see my cameras in frigate just fine, using the FQDN. However, inputting that into the host section of the settings, doesn't work. Whatever I need to provide, I will do my best to help!

**Comment by batman99000** [comment]
Interestingly, though, I have just found out that it will connect just fine if I change the protocol to http and then put tne local ip of my frigate machine. So its just an issue with the https side of things fo me spcifically. Any ideas?

**Comment by piwko28** [comment]
Try to set the port to 443. It works fine with demo server through https, so it's wrong port issue or unknown certificate.

**Comment by batman99000** [comment]
Yep that was it. Thank you!
