### ISSUE TITLE
Allow camera fullscreen live view

### ISSUE THREAD

**Issue by zajc3w** [sp-engineering/frigate-viewer#30]
A the moment app looks promising, although it's missing fullscreen liveview feature.
I would put it right after working https on priority list though.

**Comment by piwko28** [comment]
The Fullscreen live view is implemented, but it's on the early stage. You can turn it on in the settings: Camera press action. 

I plan to make it more intuitive in the future.

**Comment by zajc3w** [comment]
Oh thanks, I'll have a look at it
