### ISSUE TITLE
Settings crash on Pixel 7 Pro 

### ISSUE THREAD

**Issue by titelies** [sp-engineering/frigate-viewer#31]
Can't enable crash report send or add another server cause everytime I click Settings, the app crashes out completely. Tried clearing app cache, no difference. Premium features displays blank white page,not sure if related.

**Comment by piwko28** [comment]
Thanks for reporting. I tested it carefully, but migrations are always tough.
Clearing cache is not enough, you should clear app data or reinstall the app.
A fix is on the way, hope it will help.

**Comment by titelies** [comment]
Thank you! Fixed by clearing App Data as recommended.
