### ISSUE TITLE
Latest version is unresponsive (Android 13)

### ISSUE THREAD

**Issue by ElectronicBattle** [sp-engineering/frigate-viewer#32]
Hello

I upgraded my installed version from that of a few weeks ago to the one released on 14/10/24 but unfortunately the menu items in Frigate Viewer are hardly  accessible now.   Previously the app was working perfectly.

Problems:
At first, the app seems to start fine and the live cameras show immediately but then start flickering in turn (which the previous version didn't do)

pressing the "hamburger" icon ... several presses are needed to get the menu to show. The "list of cameras" works and the live view is fine."

All events" doesn't work at first, even after several presses (or one press and wait for many tens of seconds) ... I end up with a black screen and then after another (say) 30 s I do get the list of events showing.  Clicking on a link does not immediately play the video clip or show the thumbnail; nothing happens for perhaps 60 s then I get a blank screen for another 30 s then a "waiting" or "loading"  icon appears (the revolving circle) for another 60s and then the video finally plays.

If I want to  get into the other menu items (e.g. "logs") I need to press the menu, wait a minute or more, then see a grey screen and wait for anther minute, then eventually I get the loading icon which continues for minutes,  and then a grey screen which continues forever

I can't get into the menus to do screenshots or report logs, nor can I see the app's version number 

edit - I found "Frigate Viewer_14.2.3" on "APKPure" dated Oct 2024  so I deleted the problematic version and installed this older one, which is working properly.

Please let me know if I can help you fault find the latest release.

**Comment by piwko28** [comment]
Hey, thanks for the info.
I reported that settings structure does not migrate properly in very rare cases. Have you tried to clear app data or reinstall the app? It may help, because it will set the settings to initial values with new structure.

Please let me know if it helps.

Btw., have you had crash reporting enabled?

**Comment by ElectronicBattle** [comment]
It *did* help - thanks! I tried upgrading again and this time it worked fine. 

Yesterday, when I upgraded and had problems, I uninstalled and then added the APK as described above. In doing so, I expect I cleared out all of the app data so that today's upgrade attempt was able to succeed.

I checked and I *have* got crash reporting enabled.
