### ISSUE TITLE
App crashes when slides to Storage -> Cameras

### ISSUE THREAD

**Issue by cybersholt** [sp-engineering/frigate-viewer#4]
Recently started having some treads crashing so have been checking my logs, I noted that when dark mode is enabled that theres an overlay applied and it makes the text hard to read. I've attached some screenshots. While checking I also noticed that:

> Accent colors seem random which is fine but it does occasionally pick very similar colors, it would be great if the user could pick the accent colors or something like primary and secondary?

> Storage second tab: when I switch to that app crashes every time, I attached a screen recording.

> System version, keeps saying there's a new version but no update available? 

Keep up the great work and let me know if you need help with anything. 

![Screenshot_20231229_111925_FrigateViewer](https://github.com/sp-engineering/frigate-viewer/assets/1348086/c41a4103-edfe-4611-a5d2-761c46a426e1)
![Screenshot_20231229_111931_FrigateViewer](https://github.com/sp-engineering/frigate-viewer/assets/1348086/8a9f78d2-0518-4a66-aedd-6e4090b2ab5e)
![Screenshot_20231229_110408_FrigateViewer](https://github.com/sp-engineering/frigate-viewer/assets/1348086/3f82a207-f85a-4d67-ad3a-3fe7272a9c76)
![Screenshot_20231229_110726_FrigateViewer](https://github.com/sp-engineering/frigate-viewer/assets/1348086/eef6face-631e-4c19-be1f-96d373728d30)

https://github.com/sp-engineering/frigate-viewer/assets/1348086/ec533db6-5393-4a6f-8f0d-f0479444e263

![Screenshot_20231229_105846_FrigateViewer](https://github.com/sp-engineering/frigate-viewer/assets/1348086/8ec2a9f4-2e36-4395-8348-c29c17313ccb)
![Screenshot_20231229_110034_FrigateViewer](https://github.com/sp-engineering/frigate-viewer/assets/1348086/8e6c671d-6a23-4674-be35-8db2d37b4ed0)

**Comment by cybersholt** [comment]
Forgot to include some device info. 

It's a Samsung SM-A515U1 running android 13.

![Screenshot_20231229_112625_Settings](https://github.com/sp-engineering/frigate-viewer/assets/1348086/e90d2b37-f62c-4b92-b7ab-a0b1994d245a)
![Screenshot_20231229_112632_Settings](https://github.com/sp-engineering/frigate-viewer/assets/1348086/4d0f1e4d-91b7-4386-8d57-7bb08e8c6200)

**Comment by cybersholt** [comment]
@piwko28 forked a copy and will fix this and submit a PR. Looks like it just need's a little rework to support devices in dark mode.

**Comment by piwko28** [comment]
Thanks for raising the issue.
I broke down this issue to smaller ones, because there are more than one issue.

I read all your PR and applied some changes, but I could miss something.
Could you please point me which chunk of your code is responsible for fixing the app crash?

**Comment by piwko28** [comment]
The version with the fix is currently on the Play store. Let me know if the issue still occur.
