### ISSUE TITLE
Event playback doesn't work when HTTP auth is enabled 

### ISSUE THREAD

**Issue by potchin** [sp-engineering/frigate-viewer#5]
Pretty sure this has broken in the latest release - when trying to view any of my captured events I just get a white screen with no video playback. Tapping results in a play/pause icon but no video frames are ever shown.

Pixel 8 (Android 14)

**Comment by piwko28** [comment]
Which version of the application do you use? There were few updates within last few days.

**Comment by potchin** [comment]
1.3.2

**Comment by potchin** [comment]
Actually this is related to #1, when bypassing http auth it works as expected. With http auth enabled event playback fails

**Comment by potchin** [comment]
Any ideas @piwko28? Bit of a shame to have HTTP auth only partially supported

**Comment by ozziii** [comment]
Same issue...  No event playback

app version 1.3.2  
frigate version 0.13.2-6476F8A
source: video h264 + audio AAC 
reverse proxy: Traefik basicAuth

**Comment by piwko28** [comment]
More details needed. It works well with demo server, which is through https. Is it still an issue?

**Comment by piwko28** [comment]
Ach, it's about authentication. Thanks for clarification, I'll take a look.

**Comment by piwko28** [comment]
Authentication header is attached correctly. I need a frigate server with basic auth authentication to understand the matter of the issue.

**Comment by potchin** [comment]
@piwko28 I've setup a proxy to the official frigate demo server..

`https://frigatedemo.potchin.co.uk/`
Username is your gh user, pass is `demo`.

Let me know how you get on, ill delete it once the bug is fixed :)

**Comment by piwko28** [comment]
Oh, thanks, good idea!

**Comment by piwko28** [comment]
The bug is fixed, will be released with next update. Let me know if works.

**Comment by potchin** [comment]
Great, thanks. I've removed the demo server. I assume that'll be in the next release after 14.0.0? (I received that today and it doesnt yet have the fix)

**Comment by piwko28** [comment]
Yes, the one after 14.0.0.

**Comment by potchin** [comment]
Confirmed fixed in 14.1.0, thanks @piwko28
